apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: garmadon
  description: Observability of your Hadoop job
  tags:
    - java
  annotations:
    backstage.io/techdocs-ref: github:https://github.com/criteo-dexter/garmadon
    github.com/project-slug: criteo/garmadon
    travis-ci.com/repo-slug: criteo-dexter/garmadon
spec:
  type: service
  lifecycle: production
  owner: lake@criteo.com
